source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'BanTang' do
pod 'SnapKit'
pod 'SDCycleScrollView'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'    
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'SDWebImage'


end